package com.raj.domain.model;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author WhiteWolf
 */
@DynamoDBTable(tableName = "medicine_store")
public class MedicineStore implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBRangeKey
	private String medName;
	
	@DynamoDBAttribute
	private String batchNo;
	
	@DynamoDBAttribute
	private Date manfDate;
	@DynamoDBAttribute
	private Date expDate;
	
	@DynamoDBAttribute
	private int qty;
	
	@DynamoDBAttribute
	private BigDecimal unitPrice;

	@DynamoDBAttribute
	private BigDecimal sellingPrice;
	@DynamoDBAttribute
	private Date dateCreated;
	
	@DynamoDBAttribute
	private Date dateUpdated;
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "manufacturerId",attributeName="manufacturerId" )
	private Integer manufacturerId;
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "medicineCategoryId",attributeName="medicineCategoryId")
	private Integer medicineCategoryId;



	/**
	 * @return the manufacturerId
	 */
	 public Integer getManufacturerId() {
		 return manufacturerId;
	 }

	 /**
	  * @param manufacturerId the manufacturerId to set
	  */
	 public void setManufacturerId(Integer manufacturerId) {
		 this.manufacturerId = manufacturerId;
	 }

	 /**
	  * @return the medicineCategoryId
	  */
	 public Integer getMedicineCategoryId() {
		 return medicineCategoryId;
	 }

	 /**
	  * @param medicineCategoryId the medicineCategoryId to set
	  */
	 public void setMedicineCategoryId(Integer medicineCategoryId) {
		 this.medicineCategoryId = medicineCategoryId;
	 }
	 
	 @DynamoDBAttribute
	 private String medDose;
	 @DynamoDBAttribute
	 private String medDesc;
	 @DynamoDBAttribute
	 private String medType;

	 public MedicineStore() {
	 }

	 public MedicineStore(String id) {
		 this.id = id;
	 }

	 public MedicineStore(String id, String medName, String batchNo, Date manfDate, Date expDate, int qty, BigDecimal unitPrice, BigDecimal sellingPrice, Date dateCreated, Date dateUpdated) {
		 this.id = id;
		 this.medName = medName;
		 this.batchNo = batchNo;
		 this.manfDate = manfDate;
		 this.expDate = expDate;
		 this.qty = qty;
		 this.unitPrice = unitPrice;
		 this.sellingPrice = sellingPrice;
		 this.dateCreated = dateCreated;
		 this.dateUpdated = dateUpdated;
	 }

	 public String getId() {
		 return id;
	 }

	 public void setId(String id) {
		 this.id = id;
	 }

	 public String getMedName() {
		 return medName;
	 }

	 public void setMedName(String medName) {
		 this.medName = medName;
	 }

	 public String getBatchNo() {
		 return batchNo;
	 }

	 public void setBatchNo(String batchNo) {
		 this.batchNo = batchNo;
	 }

	 public Date getManfDate() {
		 return manfDate;
	 }

	 public void setManfDate(Date manfDate) {
		 this.manfDate = manfDate;
	 }

	 public Date getExpDate() {
		 return expDate;
	 }

	 public void setExpDate(Date expDate) {
		 this.expDate = expDate;
	 }

	 public int getQty() {
		 return qty;
	 }

	 public void setQty(int qty) {
		 this.qty = qty;
	 }

	 public BigDecimal getUnitPrice() {
		 return unitPrice;
	 }

	 public void setUnitPrice(BigDecimal unitPrice) {
		 this.unitPrice = unitPrice;
	 }

	 public BigDecimal getSellingPrice() {
		 return sellingPrice;
	 }

	 public void setSellingPrice(BigDecimal sellingPrice) {
		 this.sellingPrice = sellingPrice;
	 }

	 public Date getDateCreated() {
		 return dateCreated;
	 }

	 public void setDateCreated(Date dateCreated) {
		 this.dateCreated = dateCreated;
	 }

	 public Date getDateUpdated() {
		 return dateUpdated;
	 }

	 public void setDateUpdated(Date dateUpdated) {
		 this.dateUpdated = dateUpdated;
	 }
	 public void setDateUpdated(String dateUpdated) {
		 this.dateUpdated = null;
	 }


	 @Override
	 public int hashCode() {
		 int hash = 0;
		 hash += (id != null ? id.hashCode() : 0);
		 return hash;
	 }

	 @Override
	 public boolean equals(Object object) {
		 // TODO: Warning - this method won't work in the case the id fields are not set
		 if (!(object instanceof MedicineStore)) {
			 return false;
		 }
		 MedicineStore other = (MedicineStore) object;
		 if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
			 return false;
		 }
		 return true;
	 }

	 

	 /* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "MedicineStore [id=" + id + ", medName=" + medName + ", batchNo=" + batchNo + ", manfDate=" + manfDate
				+ ", expDate=" + expDate + ", qty=" + qty + ", unitPrice=" + unitPrice + ", sellingPrice="
				+ sellingPrice + ", dateCreated=" + dateCreated + ", dateUpdated=" + dateUpdated + ", manufacturerId="
				+ manufacturerId + ", medicineCategoryId=" + medicineCategoryId + ", medDose=" + medDose + ", medDesc="
				+ medDesc + ", medType=" + medType + "]";
	}

	public String getMedDose() {
		 return medDose;
	 }

	 public void setMedDose(String medDose) {
		 this.medDose = medDose;
	 }

	 public String getMedDesc() {
		 return medDesc;
	 }

	 public void setMedDesc(String medDesc) {
		 this.medDesc = medDesc;
	 }

	 public String getMedType() {
		 return medType;
	 }

	 public void setMedType(String medType) {
		 this.medType = medType;
	 }



}
